### ISSUE TITLE
Analysis pod created

### ISSUE THREAD

**Issue by brucetony** [PrivateAIM/node-ui#66]
Add buttons to the Analysis Table that will allow a pod to be created for the given analysis (as well as a button to stop it)

**Comment by brucetony** [comment]
Getting error from PO currently.

Request:
```bash
curl -X 'POST' \
  'http://localhost:8081/po' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer XXX' \
  -H 'Content-Type: application/json' \
  -d '{
  "analysis_id": "e3d2f86d-97d4-44c7-8371-f6899051dd9c",
  "project_id": "8b7b1a8e-0bf0-4f01-ba5b-d7169f300c13"
}'
```

Error:
```python
INFO:     192.168.178.45:49046 - "GET /po/healthz HTTP/1.1" 200 OK
INFO:     127.0.0.1:49212 - "POST /po HTTP/1.1" 307 Temporary Redirect
Exception: HTTPConnectionPool(host='flame-node-kong-admin', port=80): Max retries exceeded with url: /consumers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c2fc8777d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Exception: cannot access local variable 'consumer_id' where it is not associated with a value

Exception: cannot access local variable 'consumer_id' where it is not associated with a value

INFO:     127.0.0.1:49212 - "POST /po/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/api/api.py", line 31, in create_analysis
    analysis.start(database)
  File "/app/src/resources/analysis/entity.py", line 30, in start
    self.tokens = create_tokens(self.deployment_name, self.analysis_id, self.project_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/utils/token.py", line 20, in create_tokens
    'KEYCLOAK_TOKEN': _get_keycloak_token(analysis_id)}
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/utils/token.py", line 28, in _get_keycloak_token
    client_secret = _get_keycloak_client_secret(analysis_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/utils/token.py", line 46, in _get_keycloak_client_secret
    admin_token = _get_keycloak_admin_token()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/utils/token.py", line 77, in _get_keycloak_admin_token
    response.raise_for_status()
  File "/app/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://foo-keycloak/realms/flame/protocol/openid-connect/token
```

**Comment by brucetony** [comment]
Fixed and implemented
